### PR TITLE
Update dispatch-bazaar.yml

### PR DESCRIPTION
**Pull request by pattacini**
Yet another try after #519, which integrates these [suggestions](https://github.com/actions/create-release/issues/25#issuecomment-562687270) for multi lines.

🤞🏻

### CODE REVIEW

**Review by vtikha — APPROVED** [review]
yep, seems legit 😄

**Comment by pattacini** [comment]
The action just failed. I'm going to disable the workflow so that we'll have time to do debugging.

**Comment by vtikha** [comment]
I am with @AlexAntn looking at it

**Comment by pattacini** [comment]
Play with it if you find anything relevant.

**Pull request merged**
